# Path to the Word document in a directory that OneDrive syncs to the cloud
document_path = "/path/to/file"

# The text that will be written to the file. Copy each paragraph of the source essay on to a new line, surrounded by double-quotes, with a comma at the end of each line except the last.
input_text = [
    "Creatine monohydrate is one of the most researched and widely used supplements in the fitness and sports nutrition industry. Found naturally in foods like meat and fish, as well as synthesized in the human body, creatine plays a crucial role in energy production during high-intensity physical activity. For those who work out, supplementing with creatine monohydrate can provide numerous benefits, enhancing both performance and overall fitness outcomes.",
"Creatine is a compound stored primarily in skeletal muscles, where it exists in both free form and as phosphocreatine. Phosphocreatine is a high-energy molecule that donates a phosphate group to adenosine diphosphate (ADP), regenerating it into adenosine triphosphate (ATP), the body's primary energy currency. This process is particularly important during short bursts of high-intensity activities, such as weightlifting, sprinting, and jumping. By increasing phosphocreatine stores, creatine supplementation enables quicker ATP regeneration, allowing for improved performance in activities that require short, intense effort. Studies consistently show that creatine enhances strength, power, and the ability to perform repeated bouts of high-intensity exercise.",
"Beyond its effects on performance, creatine indirectly promotes muscle hypertrophy by enabling users to lift heavier weights and complete more repetitions. Additionally, creatine draws water into muscle cells, increasing cell volume. This process, called cell volumization, may signal anabolic pathways and contribute to muscle growth over time. Moreover, creatine’s ability to reduce muscle damage and inflammation following intense workouts can significantly speed up recovery. It also helps replenish phosphocreatine stores more quickly post-exercise, preparing the body for subsequent sessions. While its primary benefits are seen in physical performance, creatine also supports cognitive function. Research suggests that it may improve mental clarity and reduce fatigue, especially during tasks requiring high focus or problem-solving.",
"One of the most compelling reasons for people who work out to use creatine is its proven safety and efficacy. Creatine monohydrate is one of the safest and most scientifically validated supplements available. Decades of research have confirmed its effectiveness in improving strength, muscle mass, and performance, with minimal risks when used as directed. Its benefits are not limited to elite athletes; creatine can enhance the performance of recreational gym-goers and those new to fitness. By enabling users to train harder and recover faster, it serves as a versatile supplement that aligns with a wide range of fitness goals.",
"Another advantage of creatine is its cost-effectiveness. Compared to other supplements, creatine monohydrate is highly affordable and delivers significant results for a relatively small investment. Its convenience adds to its appeal; creatine is easy to use, typically taken as a powder mixed with water or added to pre- or post-workout shakes. A standard dose of 3-5 grams per day is sufficient for most users, making it a simple yet powerful addition to any fitness routine.",
"Creatine monohydrate is a game-changer for individuals looking to maximize their workout performance and recovery. Its ability to enhance strength, power, and muscle growth, along with its safety and affordability, make it an ideal choice for fitness enthusiasts. By incorporating creatine into their routines, people can push past plateaus, achieve greater results, and enjoy a more rewarding fitness journey."
]